language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install .
# command to run tests
script: trial cooperative.tests
